### ISSUE TITLE
Dataset not available

### ISSUE THREAD

**Issue by SunnyBoyka** [apurvnnd/Multiple-Image-Recognition-CNN#1]
Dataset not available

**Comment by apurvnnd** [comment]
Updated the link, try again.

**Comment by sazidabintaislam** [comment]
What If I want to use my won imagery data set. Where I need to make changes.

**Comment by apurvnnd** [comment]
@sazidabintaislam those have been mentioned in the readme, you can get an idea going through the code as well. Apologies for reallyyy late response.
